[package]
name = "docbrown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roaring="0.10"
# dashmap="5"
itertools="0.10"
# guardian = "1.0.2"
csv = "1.1.6"
replace_with = "0.1"
thiserror = "1"
rayon = "1"
crossbeam = "0.8"
rand = "0.8.5"
# packed_struct = "0.10"
 sorted_vector_map = "0.1"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "tgraph_benchmarks"
harness = false

[profile.release]
debug = 1

[rust]
debuginfo-level = 1
