[package]
name = "docbrown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roaring="0.10"
dashmap="5"
itertools="0.10"
guardian = "1.0.2"
csv = "1.1.6"
rayon = "1.6"
replace_with = "0.1"
